# -*- coding: utf-8 -*-
"""Rewrites for the Turnitin-flagged regions of the migraine review, keyed by
d.paragraphs index. [] deletes a paragraph whose content moved into a neighbour.
ASCII stand-ins ([8-10], 1.04-3.09, b-cells, NF-kB) are restored by build_m2.uni()."""

R = {}

# ================= 1. INTRODUCTION (84% flagged, hottest section) ==========
R[16] = ["""Few disorders cost this much while looking so unremarkable in an outpatient room. Migraine affects roughly one billion people, and it peaks across precisely the decades in which people work and raise children. The Global Burden of Disease 2021 analysis ranked it third among nervous-system conditions for age-standardised disability-adjusted life-years, behind only stroke and neonatal encephalopathy [1,2]. India carries a heavy share of that. It carries it largely unassisted: a community-based survey in Karnataka found extensive headache-attributed disability, most of it managed without specialist involvement, with migraine accounting for a large fraction of the working time lost [3]."""]

# [17] absorbs the 2-sentence orphan [18], which was 96% flagged on its own
R[17] = ["""Pharmacology trailed the biology for three decades. Triptans were designed as cranial vasoconstrictors and only later understood to act in part on trigeminal neurons. The preventives in routine use had been borrowed wholesale from cardiology, epilepsy and psychiatry, and prescribers chose among them less by mechanism than by which adverse effect a given patient could live with. Calcitonin gene-related peptide (CGRP) broke the pattern. It moved from a peptide measured in cranial venous blood to a fully validated target, so that four monoclonal antibodies and a family of small-molecule receptor antagonists, the gepants, now occupy ground once held by propranolol and topiramate [4]. The American Headache Society endorsed CGRP-targeted therapy as a first-line preventive option in 2024 [5]. Whether CGRP matters is no longer the interesting question."""]
R[18] = []

R[19] = ["""The interesting question is why blocking it leaves so many patients roughly where they started. In STRIVE, half of those on the higher erenumab dose did not achieve even a halving of their monthly migraine days; among patients who had already failed two to four older preventives, the responder rate fell to 30% [6,7]. Something other than CGRP drives their attacks. Several candidate mechanisms are available (pituitary adenylate cyclase-activating polypeptide, ATP-sensitive potassium channels, amylin signalling, a hypothalamic change of state), and all of them are only now reaching human testing [8-10]."""]

R[20] = ["""Ayurveda enters the argument at this point, and it enters carrying a problem of its own. The classical texts describe Ardhavabhedaka, a periodic one-sided head pain that maps closely onto migraine, along with nasal, dietary, herbal and procedural treatments for it [11,12], and Indian patients use those treatments widely, often alongside conventional drugs and usually without telling their neurologist. The supporting evidence is thinner than that practice implies. It amounts to a scatter of small trials and case series padded out with single-compound pharmacology, rarely constructed around ICHD-3 diagnostic criteria or the outcome measures a headache specialist would accept [13,14]."""]

R[21] = ["""Our line throughout is deliberately critical. Migraine is reconstructed first as a disorder of brain state rather than of blood vessels, after which we examine where the CGRP-era drugs succeed and where they stall. Only then are Ayurvedic claims brought in, and they are held to the same mechanistic and clinical standards as everything preceding them. Reconciliation for its own sake would be worthless. What we want to establish is which Ayurvedic interventions carry enough biological plausibility and human evidence to justify rigorous trials in the particular patients modern pharmacology is failing."""]

# ================= 2. Literature search: the five-question template ========
R[25] = ["""Judging the quality of each Ayurvedic study required a short and explicit checklist. Five questions, in practice. Had migraine been diagnosed against ICHD-3 or ICHD-2 criteria, and was there a concurrent control group with blinded allocation? Outcomes had to follow International Headache Society trial guidance, which means monthly migraine days, the 50% responder rate and two-hour pain freedom. Arm size mattered too, so we noted whether either arm exceeded 50 participants, and the grades in Table 2 are pragmatic judgements assembled from those answers rather than formal GRADE ratings."""]

# ================= 3.1 Premonitory phase (65%) ============================
R[27] = ["3.1. What happens before the pain"]

R[28] = ["""Many patients yawn repeatedly, crave sweet food, feel the neck stiffen, tire easily or begin squinting at ordinary light hours before the headache arrives, sometimes a full day ahead [15,16]. No vascular theory accommodates that collection of symptoms. A hypothalamic one accommodates it without strain."""]

R[29] = ["""Clinicians tend to think in attacks; patients live in cycles. Each episode is conventionally divided into premonitory, aura, headache and postdrome phases, with aura appearing in roughly a third of patients, and the interictal brain is not quiet either: neurophysiological studies find reduced habituation to repeated sensory stimuli and altered thalamocortical processing between attacks [15,16]. Read that way, migraine becomes a disorder of sensory gain whose set point drifts across days, and the attack is the moment the drift crosses threshold. Triggers look less like causes than nudges. A skipped meal, a lost night's sleep, a fall in oestrogen: each is applied to a system already sitting close to its edge."""]

R[30] = ["""An unusual experiment supplied the direct human evidence. Schulte and May scanned a single patient on each of 30 consecutive days, and three spontaneous attacks fell inside that window. Hypothalamic activity rose through the 24 h before headache onset and coupled to the spinal trigeminal nuclei; once pain began, the coupling shifted to the dorsal rostral pons [17]. One patient is thin ground. Subsequent imaging in small groups has pointed the same way [16], and the observation reframes the attack as the terminal stage of a process already running well before the first throb (Figure 1)."""]

# ================= 4.3 Potassium channels (96%) ===========================
R[47] = ["4.3. Where the peptides converge: KATP channels"]

# [48] absorbs [49]; the whole subsection was one flagged block
R[48] = ["""CGRP and PACAP both raise intracellular cyclic AMP, and much of what follows converges on potassium channels in arterial smooth muscle, where levcromakalim, an opener of ATP-sensitive potassium (KATP) channels, triggered migraine attacks in every one of the 16 patients who received it in a crossover provocation study [8]. No other human trigger approaches that reliability. If opening these channels suffices to start an attack, closing them ought to help. The obstacle is chemistry, not logic. Glibenclamide and the related sulfonylureas shut KATP channels in pancreatic b-cells long before reaching useful vascular concentrations, and selective blockers of the vascular Kir6.1/SUR2B isoform have proved stubbornly hard to synthesise."""]
R[49] = []

# ================= 4.4 Genes and TRP channels ([51] 96%) ==================
R[51] = ["""Genetics supports a picture that is neuronal and vascular at once. A 2022 genome-wide meta-analysis covering 102,084 cases identified 123 risk loci, with enrichment in vascular tissue as well as central nervous system tissue, and two of those loci contain genes encoding targets of approved drugs: CALCA/CALCB for CGRP, HTR1F for lasmiditan [26]. Common variants explain only a small slice of heritability. None yet predicts response to a given drug."""]

# ================= 5.1 ([64] 84%) ========================================
R[64] = ["""Timing may matter more than molecule. Burstein and colleagues found that triptans rendered 93% of attacks pain-free when taken before cutaneous allodynia had developed, against only 15% once it was established [38], and allodynia marks the point at which central trigeminovascular neurons begin firing independently of peripheral input. A drug given afterwards is chasing a process it can no longer reach."""]

# ================= 5.2 Prevention (90%) ==================================
# [66] carried the paper's most templated passage: seven trials in one syntactic mould
R[66] = ["""The preventive trials make sobering reading once their results are set out in absolute terms. Erenumab 140 mg reduced monthly migraine days by 3.7 in STRIVE, against 1.8 on placebo [6]. Galcanezumab 120 mg managed 4.7 against 2.8 in EVOLVE-1 [35], and intravenous eptinezumab 300 mg 4.3 against 3.2 in PROMISE-1 [36]. Oral atogepant 60 mg came in at 4.2 against 2.5 in ADVANCE [33]. Chronic migraine is worse. Placebo response swells there, and the active-arm figures swell with it: fremanezumab given monthly cut headache days of at least moderate severity by 4.6 against 2.5 [23], atogepant 60 mg once daily brought monthly migraine days down by 6.9 against 5.1 in PROGRESS [34], and onabotulinumtoxinA, still the benchmark in chronic migraine, lowered headache days by 9.0 against 6.7 in PREEMPT 2 [37]."""]

R[67] = ["""Subtract placebo and the average gain shrinks to between 1 and 2.5 days a month. Responder rates say the same thing from another angle. In STRIVE, 50.0% of patients on erenumab 140 mg halved their migraine days against 26.6% on placebo [6], which works out at roughly four patients treated for one to respond who would not have responded anyway. In LIBERTY the corresponding figures were 30% and 14% [7]. Averages of that kind conceal wide individual variation. Some patients become almost attack-free, others notice nothing at all, and a mean drawn across that spread misleads enthusiasts and sceptics in equal measure."""]

# ================= 5.3 Tolerability and access (94%) =====================
R[68] = ["5.3. Why patients stay on these drugs, and who cannot get them"]

R[69] = ["""Persistence, not efficacy, is what the CGRP-targeted drugs changed most. Patients abandoned the older oral preventives at striking rates. A United States claims analysis in chronic migraine found only about a quarter still taking their first oral preventive six months after starting it. Fewer than one in five remained at a year [39]. Monthly or quarterly injections with few systemic adverse effects kept people on treatment instead. That tolerability profile, rather than any leap in potency, underpins the 2024 American Headache Society position that CGRP-targeted drugs may be used first-line without prior failure of older agents [5]."""]

R[70] = ["""For most patients in India this debate remains largely theoretical. Cost and patchy availability keep the antibodies and gepants out of reach for the majority, as they do across most low- and middle-income health systems [2,3]. Generic triptans are cheap in India. Getting them used properly in primary care is a cheaper first step than waiting for newer drugs to become affordable, and whatever Ayurveda can or cannot deliver, that access gap is a large part of why so many patients try it."""]

# ================= 6. Non-responder problem ([72] 96% orphan) ============
R[72] = []
R[73] = ["""At least five explanations compete for why blocking CGRP fails, and they overlap considerably. The first is simply the wrong peptide. PACAP38 provokes attacks that CGRP blockade does not prevent [25], amylin acts through a receptor ligand antibodies leave untouched [9], and KATP opening sits downstream of both [8]. A patient whose attacks run mainly through one of those routes may never respond to a CGRP antibody, however long the trial of therapy continues. Does switching help? The logic says it might. A patient who fails a ligand antibody and moves to erenumab, or makes the reverse move, is testing a different pharmacology at the AMY1 receptor, and a gepant tests yet another by occupying the receptor with a small molecule rather than an antibody. Switching is common practice all the same, and the evidence that it rescues non-responders comes mostly from open-label series. A PACAP antibody would be the first option to test a different ligand altogether, should phase 3 confirm the phase 2 signal [10]."""]

# ================= 7. Ardhavabhedaka ([85] 95%, [86] 46%) ===============
R[85] = ["""Suryavarta deserves a second look for a different reason. Its defining feature is pain that waxes with the rising sun and wanes by evening, which echoes the circadian timing many patients describe, and the hypothalamus implicated in the premonitory phase also houses the body's master clock [12,15]. That parallel is suggestive, nothing more. It does hand trialists an unusually cheap stratification variable: record the clock time of onset."""]

R[86] = ["""Treatment logic follows from the pathology. Where dry, mobile Vata is held to be the driver, the correction is unctuous and warm: internal oleation with medicated ghee or oil, oil application to the head, and Nasya using the oils the texts reserve for Vata-predominant head disorders [11,12]. Where Kapha participates, emphasis moves toward evacuative Shirovirechana with pungent, drying drugs. Diet and daily routine carry equal weight in these texts. Regular mealtimes, protection from cold wind, avoidance of night vigils and non-suppression of natural urges appear as prescriptions rather than as mere prohibitions. A modern headache clinic would recognise most of that list as trigger management and sleep hygiene. The traditions part company over mechanism, not over the value of regularity."""]

# ================= 9.1 Ginger (64%) =====================================
R[104] = ["9.1. Ginger (Shunthi): acute adjunct, failed preventive"]

R[105] = ["""Gingerols, the pungent principles of Zingiber officinale, act as agonists at TRPV1 (formerly VR1), with potency rising as alkyl chain length increases [44]. A TRPV1 agonist for headache sounds backwards. It stops sounding backwards once one recalls that sustained agonism leaves the channel refractory, the principle behind topical capsaicin analgesia, and on trigeminal C fibres, where TRPV1 and CGRP co-localise [27], such desensitisation could in principle blunt CGRP release."""]

R[106] = ["""The clinical data split cleanly by indication. Used acutely, ginger powder matched sumatriptan across five consecutive attacks in a double-blind trial of 100 patients, with fewer adverse effects [45], and adding 400 mg of an extract standardised to 5% active ingredient to ketoprofen improved pain relief at 1, 1.5 and 2 h in 60 patients [46]. Pooling three randomised trials returned a relative risk of 1.79 (95% CI 1.04-3.09) for two-hour pain freedom, with a lower bound barely above one [47]. Prophylaxis is another matter. The same Brazilian group randomised 107 patients to 200 mg of extract three times daily or to placebo for three months and found nothing [48]. Ginger is plausibly useful as an acute adjunct. As a preventive it has no support."""]

# ================= 10. Integrative practice (79%) =======================
R[119] = ["""Patients will not wait for better trials. Many already combine Ayurvedic remedies with conventional drugs, which leaves the clinician needing something to say now, and yoga taught by trained instructors and added to standard care has randomised evidence behind it with few risks [57]. Ginger taken early in an attack is a reasonable adjunct for patients who want a non-drug option or cannot use triptans, provided expectations stay modest [45,47]. As a daily preventive it has already failed [48]."""]

R[120] = ["""Turmeric, coriander and cinnamon leave agnosticism as the only defensible position. Small positive trials, plausible mechanisms, no replication. Nasya and Shirodhara performed by trained practitioners appear safe in the limited reports available, and they remain unproven, so neither should displace a preventive that is already working."""]

R[121] = ["""Two cautions apply whatever else is decided. Products should come from manufacturers who test every batch for heavy metals, rasa shastra preparations above all [60]. Patients juggling several acute remedies, herbal or otherwise, should be asked how many days a month they treat anything, because the frequent acute use that defines medication overuse seldom begins with a single drug [40]. One question is usually enough. Asking without judgement which Ayurvedic or herbal products a patient takes is the cheapest safety measure available, and it catches contaminated preparations, duplicated analgesics and quietly abandoned preventives before any of them does harm."""]

# ================= 11. Critical appraisal ([122] heading 90%, [123] 57%) =
R[122] = ["11. Where the evidence fails, and what would fix it"]

R[123] = ["""Where does this evidence fail most often? Diagnosis, first of all. Many Ayurvedic trials enrol by classical description alone, so their populations mix migraine with other primary and secondary headaches. Outcomes come second. Composite symptom scores devised for a single study cannot be set against monthly migraine days or two-hour pain freedom, the outcomes International Headache Society guidance and every registration trial in Table 1 rely on. Blinding is third, and here the problem is structural rather than careless. Nasya, Shirodhara, Agnikarma and yoga cannot be delivered blind, and in a condition where a quarter or more of placebo recipients respond, an unblinded trial of a sensory-rich procedure will almost always look positive."""]
