# -*- coding: utf-8 -*-
"""v8 rewrites of the Turnitin-flagged regions, keyed by v7 paragraph index.
A list of >1 string means the paragraph splits. [] means the paragraph is absorbed elsewhere.
ASCII stand-ins (ug/dL, NF-kB, AP-1, gut-brain, blood-brain, herb-drug, [2-4])
are restored to the manuscript's own Unicode by build_v8.uni()."""

R = {}

# ---- ABSTRACT (was 39% flagged; had 0 numerals, 0 citations) ---------------
R[3] = ["""Classical Ayurveda describes Dushi Visha as poison the body never finishes clearing. Potency weakened, it sits in the tissues doing slow damage, and surfaces only when diet, season or a lapse in host defence gives it room. Modern toxicology reports something uncomfortably close under another name: low-dose exposure sustained over decades, deposition in bone and brain, then a slow grind of oxidative stress, failing mitochondria and chronic inflammation that ends often enough in neurodegeneration. No single antidote reaches all of that. EDTA, DMSA and DMPS pull metal from blood and soft tissue, and leave the established mitochondrial and inflammatory lesion where it is. Rasayana, we argue, is better read as a systems-level strategy than as one more remedy aimed at one toxicant: several molecular and organ-level pathways at once. We test that reading against five herbs (Ashwagandha, Guduchi, Amalaki, Triphala, Brahmi) for what they do to redox signalling, transcription, apoptosis, synaptic plasticity and the gut-brain axis. Mechanism is the strong part of the case. Human evidence is not. Closest to a proof of principle is a one-month trial of 500 mg vitamin C daily in battery-plant workers whose mean blood lead sat near 63 ug/dL. Serum lipid peroxides fell about 16% and erythrocyte superoxide dismutase rose 38%; blood lead barely moved. Vitamin C is not a Rasayana. Safety runs the other way, with 43 documented cases of Tinospora-attributed liver injury and detectable lead, mercury or arsenic in one marketed Ayurvedic product in five (40.6% among rasa shastra preparations). Delivery is the weak link. Withanolides, bacosides and the larger polyphenols barely reach the brain, so we close by setting Ghrita, the classical lipid Anupana, against nanoemulsions and solid lipid nanoparticles, and by setting out the work the field still owes."""]

# ---- INTRODUCTION para 1 (its general tail was flagged) --------------------
R[6] = ["""Bone holds lead and the kidney holds cadmium, both for decades, so internal exposure continues long after the external source is gone. Mercury is the odd one out. Blood clears it within months, yet inorganic mercury deposited in the brain appears to be retained for years and possibly decades[7]. Cadmium at low dose strips glutathione out of liver and kidney mitochondria by degrees, leaving oxidative damage that accumulates[8]; lead and mercury are neurotropic and cardiotoxic alike, and may take years of dietary and environmental exposure before they declare themselves clinically[9,10]. Kinetics of a poison that does not leave, in other words, and the clinic calls the consequences latent toxicity.""",
"""Organic solvents and endocrine-disrupting chemicals behave the same way, accumulating across years of subclinical contact with little to show for it[5]; then adaptive capacity runs out and several organ systems give way at once. Fatigue, cognitive complaints, dysautonomia, metabolic derangement, chronic inflammatory disease. Vague, all of it. Nobody can date the onset, because there is rarely a single episode to name[5,6]."""]

# ---- INTRODUCTION para 2 (96% flagged -- the worst region) -----------------
R[7] = ["""An older vocabulary got there first. Charaka and Sushruta both describe Dushi Visha as poison that has lost its acute virulence and was never cleared[1]. It stays. A change of season, a dietary indiscretion, a dip in host defence: any of these wakes it[1]. Of the ten properties classical nosology attributes to Visha, Dushi Visha carries an incomplete set; that is why it kills nobody quickly and produces delayed, shifting complaints instead (indigestion, skin eruptions, oedema, neurological disturbance, progressive tissue wasting)[1].""",
"""Where it sits matters as much as what it is. Visha lodged in the deeper Dhatus and Srotas, held under Avarana by the Doshas, lies dormant until stress or poor diet overwhelms compensation[1]. Set that beside lead in bone and inorganic mercury in brain; each is retained for years, and each leaks back into the circulation to drive subclinical or overt disease[7,8]. Ayurvedic reviews now read Dushi Visha as the chronic low-dose load of pesticide residues, food adulterants and occupational chemicals often enough for it to count as the standard move[2-4]. How exact the equation is matters less than whether it earns its keep. We think it does."""]

# ---- heading "Limitations of conventional single-target therapies" (100%) --
R[19] = ["What chelation does not reach"]

# ---- that section's body (95% flagged) ------------------------------------
R[20] = ["""Standard treatment for heavy-metal toxicity still runs on EDTA, DMSA and DMPS, which handle metal in blood and some soft tissues well enough but reach brain and bone hardly at all: what is locked there stays locked, and once mitochondrial or inflammatory damage is established none of the three reverses it[15,28,29]. They also leave untouched what shapes the long-term picture: the toxin's effect on redox signalling, on immune networks, on neuroplasticity[15]. Prolonged courses cost something, too. Trace elements the body needs get stripped out alongside the metal; tolerance is worst in exactly the patients least able to absorb it[30].""",
"""So what would it take to work on the residue instead of the metal? One crude test exists. Workers in a western Maharashtra battery plant, mean blood lead near 63 ug/dL at entry, took 500 mg of vitamin C daily for a month. Blood lead barely moved. Serum lipid peroxides fell by about 16%; erythrocyte superoxide dismutase rose by 38%[31]. One month, soft endpoints, a small sample. It is also the nearest thing to a proof of principle anyone here has, which says something about the state of things, and Rasayana botanicals act on oxidative stress, on inflammation, on apoptosis and on synaptic function, which puts them in exactly the same gap[4]."""]

# ---- Guduchi: the 97%-flagged summary paragraph [28] folds into [27] ------
R[27] = ["""Among Rasayana and Vishaghna drugs Tinospora cordifolia ranks with the foremost, with immunomodulatory, antioxidant and hepatoprotective effects in many models[13]. Immunopharmacological work names cordifolioside A, magnoflorine and tinocordiside as the active constituents; they enhance phagocytosis, modulate reactive oxygen species and raise nitric oxide in neutrophils. Balanced immune stimulation, then, not blunt activation[38]. Guduchi extract given to mice raised the total white cell count, lifted the peak antibody titre to 256 (against 32 in controls) and increased splenic plaque-forming cells[39]. Those mice were healthy. What a titre of 256 in an unstressed animal tells you about immune competence worn down by years of metal exposure is a separate question, and an open one. Newer data put the herb on redox-sensitive transcription too, through Nrf2 and NF-kB[13]; add the hepatoprotective and anti-inflammatory activity and a candidate emerges for those Dushi Visha phenotypes where the liver bioactivates a toxin and systemic inflammation follows[13]. That candidacy is badly complicated by the 43 liver-injury cases in the safety section below[58]."""]
R[28] = []

# ---- Amalaki: the generic topic-sentence opener was the flagged part ------
R[30] = ["""Emblicanin A and B, the characteristic hydrolysable tannins, carry much of Amalaki's activity alongside its vitamin C and polyphenol content; the fruit behaves as a potent antioxidant and cytoprotectant[40]. Drosophila work found that dietary Amalaki Rasayana raised superoxide dismutase activity, cut reactive oxygen species and lipid peroxidation even in aged flies, and improved survival under thermal, oxidative and crowding stress (with a gain in lifespan)[41]. Fly lifespan is a weak proxy for anything clinical; we cite the study for its redox measurements, not its survival curve. The keratinocyte data go further mechanistically. Amalaki extract blocked inflammation and apoptosis in UVB-exposed human keratinocytes by inhibiting AP-1 and NF-kB and their downstream mediators, prostaglandins included. Protection therefore runs through transcriptional control of inflammatory and apoptotic signalling[42,43]."""]

# ---- stacked sub-heading, 100% flagged ----------------------------------
R[70] = ["Why so little of it reaches the brain"]

# ---- bioavailability body (86% flagged); its last line moves into [73] ---
R[71] = ["""Absorption after oral dosing is poor for withanolides, bacosides and the larger polyphenols. They dissolve badly and undergo heavy first-pass metabolism; across the blood-brain barrier only small amounts arrive. Bone and neuronal membranes defeat conventional dosage forms just as thoroughly. Where neurotoxicity dominates the phenotype, getting adequate concentrations into the central nervous system becomes the whole question. Nothing in this review matters more. Phytomedicine at large owns this problem, not Ayurveda in particular: the field is full of promising in vitro and preclinical results that failed in the clinic because the compound never arrived at the tissue in useful amounts[49]."""]

R[73] = ["""Until delivery is solved, Rasayana-based toxicology will not leave the laboratory[53]. Ayurvedic pharmaceutics addressed part of that problem long ago, empirically at least. Ghrita (clarified butter, or medicated ghee) has served as a lipid Anupana for lipophilic herbs, especially in neuropsychiatric and Rasayana prescriptions. Classical texts call it Yogavahi: a vehicle that enters the subtle channels and carries the properties of the drugs processed into it to deeper tissues, provided the preparation follows the proper Ghrita and Sneha procedures. Read pharmaceutically, Ghrita is a natural lipid matrix. It raises the solubility of lipophilic constituents, promotes lymphatic absorption and may improve brain delivery through chylomicron-mediated transport[54]. Within Agada Tantra, Sushruta prescribes Ajeya Ghrita for Dushi Visha, and Dushivishari Ajeya Ghrita has been evaluated clinically against Dushi Visha-related symptoms[55]; such medicated ghees detoxify first and rejuvenate afterwards. Proper pharmacokinetics for these preparations do not exist. Even so, the pharmaceutics anticipated by several centuries what the lipid-nanoparticle literature rediscovered in the last twenty years[54]."""]

# ---- nanocarriers (27% flagged); the 9-sentence block splits -------------
R[77] = ["""Nanocarriers offer much finer control. Particle size, surface chemistry and release profile can each be tuned; each changes how much of a herbal extract is absorbed and where it ends up. Solid lipid nanoparticles, built from physiological lipids, have carried herbal extracts with gains in oral bioavailability and stability, better central nervous system penetration and lower systemic toxicity[53]. One worked example: stearic acid solid lipid nanoparticles loaded with a bacoside-rich Bacopa extract released the drug over 24 h and stayed stable for three months[56].""",
"""Rasayana-specific evidence is thinner than that, though still encouraging. As a nanoemulsion, Withania somnifera crossed the blood-brain barrier more effectively and protected albino rats against penconazole-induced neurotoxicity[35]. Feasibility, if nothing else: a nanocarrier can deliver a Rasayana against a neurotoxic insult. The likelier route to usable bioavailability, by most reviews, is the herbal solid lipid nanoparticle, Ashwagandha-loaded systems among them; conceptually these are engineered descendants of Ghrita doing the same job with control over particle size and release[53]. Pleasing as that is, do not press it: one end of the comparison is a food, the other a manufactured colloid with a toxicology of its own. Table 2 sets the classical and modern platforms side by side."""]

# ---- network pharmacology (its tail was flagged) ------------------------
R[108] = ["""Triphala and Tinospora cordifolia have already been mapped by network pharmacology[62,63]. That is the method's natural application here. Polyherbal formulations defeat the one-drug, one-target logic of conventional pharmacology, and network approaches were built for precisely that situation: many components against many targets inside the molecular machinery of latent toxicity[61]. Put target-prediction algorithms, phytochemical databases and pathway enrichment together and the convergence points come out; Nrf2 and NF-kB lead, with apoptotic regulators and the synaptic plasticity pathways that matter in Dushi Visha behind them. Whether a model of that kind earns its keep depends on whether it changes practice. It should bite first on which herbs enter a formula and at what dose, then on the biomarkers a trial chooses to measure[61]. Those same maps flag herb-drug interactions and safety liabilities before a patient meets them, which matters a great deal once Rasayana is given alongside DMSA or EDTA[58,59]."""]

# ---- roadmap: heading plus a parallel numbered list, 94-100% flagged ----
R[109] = ["What the trials would have to look like"]
R[110] = ["""Three lines of work should come first, and they are not equally hard. Preclinical models of chronic environmental toxicity (low-dose heavy-metal or pesticide exposure, with Rasayana tested both as pre-conditioning and as post-exposure treatment) are straightforward to build, and nobody has built them. Pharmacokinetic and pharmacodynamic comparison of classical Ghrita-based preparations against nano-enabled formulations is harder; no proper pharmacokinetics exist for the Ghrita arm to begin with[54]. Phase II and III trials come last, in exposure cohorts that have actually been characterised[31]."""]
R[111] = []
R[112] = []
R[113] = []

# ---- CONCLUSION (96% flagged) ------------------------------------------
R[116] = ["""What toxicology now calls latent toxicity is, on the classical account, Dushi Visha: the product of steady low-level exposure to environmental and dietary toxins. Three things sustain it at the molecular level. Mitochondria that are failing. Inflammation that persists. A neuroimmune and metabolic balance knocked out of true. No mono-targeted antidote corrects all three, and EDTA, DMSA and DMPS do not try[15,28,29]. Rasayana herbs might. They reinforce the intrinsic antioxidant network, act on Nrf2 and NF-kB, engage anti-apoptotic and synaptic repair programmes and regulate the axis between gut and brain[14,36,45]. As a group that is a credible systems-level response to a disease with no single lesion.""",
"""Credible is not demonstrated, and the distance between the two is most of what this review has been about. Rasayana's strongest human datum remains a one-month trial of 500 mg vitamin C daily in workers carrying mean blood lead near 63 ug/dL; lipid peroxides fell about 16% and superoxide dismutase rose 38%[31]. Vitamin C is not a Rasayana. Against that sit 43 documented cases of Tinospora-attributed liver injury and detectable heavy metal in 40.6% of rasa shastra products[58,60]. For a therapy proposed against toxic load, that is an awkward position. Delivery remains the limiting step. Ghrita and engineered lipid nanoparticles come at it from opposite ends of pharmaceutical history (an empirical lipid matrix at one end, a manufactured colloid at the other), and drawing on the two together could get Rasayana compounds into deep tissues and the brain itself. What is missing is evidence of the right kind: network pharmacology to define the mechanism, preclinical work done rigorously, then controlled trials in people whose exposure is on record. Until those exist, the human evidence for Rasayana in chronic toxic exposure amounts to one supplementation study in healthy elderly volunteers[50]."""]
